iteration1_agreement_rails/rails_ag1/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/web1'=> 'pages#web1'

  get '/digital' => 'digital#home'

  get '/about' => 'digital#about'

  get '/terms' => 'digital#terms'
  get '/steps' => 'digital#steps'
  get '/agreement' => 'digital#agreement'
  get '/help' => 'digital#help'

  resources :ag3s
  resources :ag2s
  resources :ag2s
  resources :list_links
  resources :puts

end

iteration1_agreement_rails/rails_ag1/app/models/ag2.rb
class Ag2 < ActiveRecord::Base
end

iteration1_agreement_rails/rails_ag1/app/models/put.rb
class Put < ActiveRecord::Base
end

iteration1_agreement_rails/rails_ag1/app/controllers/ag2s_controller.rb
class Ag2sController < ApplicationController
  before_action :set_ag2, only: [:show, :edit, :update, :destroy]

  # GET /ag2s
  # GET /ag2s.json
  def index
    @ag2s = Ag2.all
  end

  # GET /ag2s/1
  # GET /ag2s/1.json
  def show
    
  end

  # GET /ag2s/new
  def new
    @ag2 = Ag2.new
  end

  # GET /ag2s/1/edit
  def edit
  end

  # POST /ag2s
  # POST /ag2s.json
  def create
    @ag2 = Ag2.new(ag2_params)

    respond_to do |format|
      if @ag2.save
        format.html { redirect_to @ag2, notice: 'Ag2 was successfully created.' }
        format.json { render :show, status: :created, location: @ag2 }
      else
        format.html { render :new }
        format.json { render json: @ag2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ag2s/1
  # PATCH/PUT /ag2s/1.json
  def update
    respond_to do |format|
      if @ag2.update(ag2_params)
        format.html { redirect_to @ag2, notice: 'Ag2 was successfully updated.' }
        format.json { render :show, status: :ok, location: @ag2 }
      else
        format.html { render :edit }
        format.json { render json: @ag2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ag2s/1
  # DELETE /ag2s/1.json
  def destroy
    @ag2.destroy
    respond_to do |format|
      format.html { redirect_to ag2s_url, notice: 'Ag2 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ag2
      @ag2 = Ag2.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ag2_params
      params.require(:ag2).permit(:name, :title, :author, :content, :definitions)
    end
end

iteration1_agreement_rails/rails_ag1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

iteration1_agreement_rails/rails_ag1/app/controllers/digital_controller.rb
class DigitalController < ApplicationController

  def home
  end

  def about
  end

  def terms
  end

  def steps
  end

  def agreement
  end

  def help
  end

end

iteration1_agreement_rails/rails_ag1/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

iteration1_agreement_rails/rails_ag1/app/helpers/ag2s_helper.rb
module Ag2sHelper
end

iteration1_agreement_rails/rails_ag1/app/helpers/application_helper.rb
module ApplicationHelper
end

iteration1_agreement_rails/rails_ag1/app/helpers/puts_helper.rb
module PutsHelper
end

iteration1_agreement_rails/rails_ag1/app/views/ag2s/_form.html.erb
<%= form_for(@ag2) do |f| %>
  <% if @ag2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ag2.errors.count, "error") %> prohibited this ag2 from being saved:</h2>

      <ul>
      <% @ag2.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :definitions %><br>
    <%= f.text_area :definitions %>
  </div>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

iteration1_agreement_rails/rails_ag1/app/views/ag2s/edit.html.erb
<h1>Make your changes here</h1>

<%= render 'form' %>

<%= link_to 'Show', @ag2 %> |
<%= link_to 'Back', ag2s_path %>
ß

iteration1_agreement_rails/rails_ag1/app/views/ag2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1> </h1>
<h2>All your agreements</h2>
<h3>Stored in the cloud</h3>

<p>


</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Title</th> -->
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ag2s.each do |ag2| %>
      <tr>
        <td><%= ag2.name %></td>
        <!-- <td><%= ag2.title %></td> -->
        <td><%= ag2.author %></td>
        <td><%= link_to 'View', ag2 %></td>
        <td><%= link_to 'Edit', edit_ag2_path(ag2) %></td>
        <!-- <td><%= link_to 'Destroy', ag2, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a new agreement', new_ag2_path %>

iteration1_agreement_rails/rails_ag1/app/views/ag2s/new.html.erb
<h1>Please upload a new agreement</h1>

<%= render 'form' %>

<%= link_to 'Back', ag2s_path %>

iteration1_agreement_rails/rails_ag1/app/views/ag2s/show.html.erb
<p id="notice"><%= notice %></p>


<h3>Wow! Look! There are these things called hyperlinks!</h3>

<hr>


<p>
  <strong>Name:<strong>
  <%= @ag2.name %>
</p>



<p>
  <strong>Title:</strong>
  <%= @ag2.title %>
</p>


<p>
  <strong>Operative clauses:</strong>
  <% content = @ag2.content %>
  <% dictionary = @ag2.definitions.scan(/<dt>(.+)<\/dt>/) %>
  <%# words = ["dictionary", "completion", "vendor"] %>
  <% content = content.gsub(/(#{dictionary.join("|")})/i, "<a href=\"##{'\1'}\">#{'\1'}</a>") %>
  <% content = content.gsub(/dictionary/i, "<a href='#dictionary'>dictionary</a>") %>

  <%= content.html_safe %>

</p>

<p>
  <strong>Definitions:</strong>
  <% definitions = @ag2.definitions %>
  <% definitions = definitions.gsub(/<dt>(.+)<\/dt>/i, "<dt id=\"#{'\1'}\">#{'\1'}</dt>")%>
  <%= definitions.html_safe %>

</p>


<p>
  <strong>Author:</strong>
  <%= @ag2.author %>
</p>

<%= link_to 'Edit', edit_ag2_path(@ag2) %> |
<%= link_to 'Back', ag2s_path %>

iteration1_agreement_rails/rails_ag1/app/views/digital/_persistent_nav.html.erb
<!-- <h2>Law goes the full digital monty!</h2> -->

<nav>
<div class="nav-wrapper">
  <!-- <a href="/help" class="brand-logo left">Help</a> -->
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li<a href="/about"><class="waves-effect waves-light">About this agreement</a></li>
      <li><a href="/steps"><class="waves-effect waves-light"></a></li>
      <li><a href="/terms"><class="waves-effect waves-light"></a></li>
      <li><a href="/agreement"><class="waves-effect waves-light"></a></li>

    </ul>
  </div>
</nav>




<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="/about">About</a></li>
        <li class="tab col s3"><a href="/steps">Key steps</a></li>
        <li class="tab col s3"><a href="/terms">Key terms</a></li>
        <li class="tab col s3"><a href="/agreement">The document</a></li>
      </ul>
    </div>
    <!-- <div id="test1" class="col s12">About the agreement</div>
    <div id="test2" class="col s12">Key steps</div>
    <div id="test3" class="col s12">Key terms</div>
    <div id="test4" class="col s12">The document you signed</div> -->
  </div>

<!-- <li class="pure-menu-item"><a href="/about" class="pure-menu-link">About this agreement</a></li>

<li class="pure-menu-item"><a href="/steps" class="pure-menu-link">Key steps or stages</a></li>

<li class="pure-menu-item pure-menu-selected"><a href="terms" class="pure-menu-link">Key terms</a></li>

<li class="pure-menu-item"><a href="agreement" class="pure-menu-link">Ye old fashioned agreement</a></li>

<li class="pure-menu-item"><a href="help" class="pure-menu-link">Help</a></li>


get '/digital' => 'digital#home'

get '/about' => 'digital#about'

get '/terms' => 'digital#terms'
get '/steps' => 'digital#steps'
get '/agreement' => 'digital#agreement'
get '/help' => 'digital#help' -->

iteration1_agreement_rails/rails_ag1/app/views/digital/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>About</title>
</head>
<body>


<h1>Here is the about page</h1>

<%= render "persistent_nav" %>




</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/digital/help.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Help</title>
</head>
<body>



<h1>Betty. We're here to help!</h1>

<%= render "persistent_nav" %>

</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/digital/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Digital home</title>
</head>
<body>




<h2>Law goes the full digital monty!</h2>

<%= render "persistent_nav" %>



<div class="banner">
    <h1 class="banner-head">
      <span class=" blue-text darken-text">
    <i>Agreements made simple.<br>
    Understand what you sign.</i>
  </span>
</h1>
</div>

</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/digital/steps.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Steps</title>
</head>
<body>

  <h1>Key stages of the agreement</h1>

  <%= render "persistent_nav" %>

  <div class="row">

        <!-- <div class="col s12">
          <h2>The key stages of the sale</h2>
        </div> -->

        <div class="col s4">
          <div class="row">
          <h5>Step 1</h5>
          <div class="card blue lighten-3">
                <div class="card-content white-text">
                  <span class="card-title">You've signed!</span>
                    <p>Congratulations!  Now you need to look after the business, while you wait for the time to come to receive the money. </p>
                  </div>
          </div>
        </div>
      </div>




      <div class="col s4">
        <div class="row">
          <h5>Step 2</h5>
        <div class="card blue lighten-3">
              <div class="card-content white-text">
                  <span class="card-title">The middle bit!</span>
                    <p>The buyer's going to be double checking everything to make sure it's all ok.  It's called due diligence. You also need to look after it.</p>
                </div>
        </div>
      </div>
    </div>


    <div class="col s4">
      <div class="row">
      <h5>Step 3</h5>
      <div class="card blue lighten-3">
            <div class="card-content white-text">
                <span class="card-title">Show me the money!</span>
                  <p>The last step is "completion".  This is when the buyer will pay you lots of money, and you will give them all the keys</p>
              </div>
      </div>
    </div>
  </div>

        <!-- <div class="col s3">This div is 6-columns wide</div> -->






</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/digital/terms.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Terms</title>
</head>
<body>

  <h1>Here is the key terms page</h1>

  <%= render "persistent_nav" %>


  <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header"><i class="material-icons"></i>Clause 1 - cooling off</div>
        <div class="collapsible-body">  <p class="collapse_text">1.1	Subject to clause 1.2, the Purchaser may terminate this contract by giving written notice to the Vendor (or the Vendor's agent) within 3 Business Days after the day the Purchaser signs the contract.</p>
          <p>1.2	The Purchaser is not entitled to give notice under clause 1.1 where the Purchaser previously signed a similar contract for the purchase of the Business.</p>
          <p>1.3	If the Purchaser terminates this contract under clause 1.1, any payment the Purchaser made to the Vendor or Stakeholder must be refunded.</p></div>
      </li>






      <li>
        <div class="collapsible-header"><i class="material-icons"></i>Clause 2 - Sale and Purchase</div>
        <div class="collapsible-body"><p>If all Conditions are satisfied, at Completion:<p>
        <p>2.1	the Vendor (as legal and beneficial owner) sells; and</p>
        <p>2.2	the Purchaser buys, free from all Encumbrances (other than those Encumbrances listed in the Particulars), the Business and the Assets.</p></div>
      </li>
      <li>
        <div class="collapsible-header"><i class="material-icons"></i>Clause 3 - Conditions</div>
        <div class="collapsible-body"><p><p>3.1	The rights and obligations of the parties in this contract have no force or effect until all Conditions are satisfied.</p>
        <p>3.2	Each party must:</p>
        <p>3.2.1	immediately notify the other party of the satisfaction of its Conditions; and</p>
        <p>3.2.2	provide evidence to establish, to the reasonable satisfaction of the other party, that its Conditions have been satisfied.</p>
        <p>3.3	If the Conditions are not satisfied or waived by the Purchaser on or before:</p>
        <p>3.3.1	5:00 pm, two Business Days prior to the Completion Date; or</p>
        <p>3.3.2	such other date and time agreed in writing by the parties,</p>
        <p>this contract terminates immediately, except with regard to:</p>
        <p>3.3.3	the Deposit; and</p>
        <p>3.3.4	the Confidential Information.</p></p></div>
      </li>
    </ul>
</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAg1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




  <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">CounterPoint Services</a>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/ag2s">Law goes cloud</a></li>
          <li><a href="/web1"">Law goes web 0.5</a></li>
          <li><a href="/ag2s/4">Law goes web 1.0</a></li>
          <li><a href="/digital">Law goes digital</a></li>



        </ul>
      </div>



        </nav>

        <div class="container">
<%= yield %>


  </div>

</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Here again</title>
</head>
<body>
  <h1>Digitising law?</h1>

  <h3>A thought experiment</h3>
  <h4>...in...</h4>
  <H5>bringing the law </H5>
  <h1>into the 21st century</h1>

</body>
</html>

iteration1_agreement_rails/rails_ag1/app/views/puts/_form.html.erb
<%= form_for(@put) do |f| %>
  <% if @put.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@put.errors.count, "error") %> prohibited this put from being saved:</h2>

      <ul>
      <% @put.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

iteration1_agreement_rails/rails_ag1/app/views/puts/edit.html.erb
<h1>Editing Put</h1>

<%= render 'form' %>

<%= link_to 'Show', @put %> |
<%= link_to 'Back', puts_path %>

iteration1_agreement_rails/rails_ag1/app/views/puts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Puts</h1>
<h2>I think this is my home page</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puts.each do |put| %>
      <tr>
        <td><%= put.name %></td>
        <td><%= put.content %></td>
        <td><%= link_to 'Show', put %></td>
        <td><%= link_to 'Edit', edit_put_path(put) %></td>
        <td><%= link_to 'Destroy', put, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Put', new_put_path %>

iteration1_agreement_rails/rails_ag1/app/views/puts/new.html.erb
<h1>New Put</h1>

<%= render 'form' %>

<%= link_to 'Back', puts_path %>

iteration1_agreement_rails/rails_ag1/app/views/puts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @put.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @put.content %>
</p>

<%= link_to 'Edit', edit_put_path(@put) %> |
<%= link_to 'Back', puts_path %>